version: "3.9"  # optional since v1.27.0
services:
    cssource:
        build:
            context: .
            dockerfile: cssource.dockerfile
        ports:
            - "27015:27015/udp"
        volumes:
            - data:/data
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - "8080:80"
        volumes:
            - data:/data
        depends_on:
            - cssource
volumes:
    data: { }
