version: "3.9"  # optional since v1.27.0
services:
    cssource:
        build:
            context: .
            dockerfile: cssource.dockerfile
        ports:
            - "27015:27015/tcp"
            - "27015:27015/udp"
        volumes:
            - data:/data
        restart: unless-stopped
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - "27080:80"
            - "27081:81"
        volumes:
            - data:/data
        depends_on:
            - cssource
        restart: unless-stopped
volumes:
    data: { }
