version: "3.9"  # optional since v1.27.0
services:
    csgo:
        build:
            context: .
            dockerfile: csgo.dockerfile
        ports:
            - "27016:27016/tcp"
            - "27016:27016/udp"
        volumes:
            - csgo_data:/data
        restart: unless-stopped
    cssource:
        build:
            context: .
            dockerfile: cssource.dockerfile
        ports:
            - "27015:27015/tcp"
            - "27015:27015/udp"
        volumes:
            - css_data:/data
        restart: unless-stopped
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - "27080:80"
            - "27081:81"
        volumes:
            - css_data:/data
        depends_on:
            - cssource
        restart: unless-stopped
volumes:
    css_data: { }
    csgo_data: { }
